### ISSUE TITLE
Small CSS bugs

### ISSUE THREAD

**Issue by TheRangor** [Nixhatter/CMS#16]
![13690738_661883530634158_5200949209010859739_n](https://cloud.githubusercontent.com/assets/11698006/16965448/bf861216-4dc5-11e6-8023-b90824cacf11.jpg)
![13719503_661883533967491_7041504842438620476_o](https://cloud.githubusercontent.com/assets/11698006/16965449/bf885e5e-4dc5-11e6-8fca-95dc055ea7fd.jpg)
![13775480_661883537300824_1872622907400319900_n](https://cloud.githubusercontent.com/assets/11698006/16965451/bf89d89c-4dc5-11e6-84d2-128658533521.jpg)
![13782172_661883527300825_3348802922570037857_n](https://cloud.githubusercontent.com/assets/11698006/16965450/bf8980d6-4dc5-11e6-807e-e734690b6a0a.jpg)

**Comment by Nixhatter** [comment]
@TheRangor Fixed most of these issues in his commit, 1a5632f987e50a8582abdf18a98740d8bc3c0ef8
